// <auto-generated />
using System;
using DziennikMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DziennikMVC.Migrations
{
    [DbContext(typeof(DziennikDbContext))]
    [Migration("20210411220054_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DziennikMVC.Models.Klasa", b =>
                {
                    b.Property<int>("KlasaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NauczycielId")
                        .HasColumnType("int");

                    b.Property<string>("nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlasaId");

                    b.ToTable("Klasa");
                });

            modelBuilder.Entity("DziennikMVC.Models.Konto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("NauczycielId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("UczenId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pesel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NauczycielId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UczenId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("DziennikMVC.Models.Lekcja", b =>
                {
                    b.Property<int>("LekcjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KlasaId")
                        .HasColumnType("int");

                    b.Property<int>("NauczanieId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("date")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("LekcjaId");

                    b.HasIndex("KlasaId");

                    b.HasIndex("NauczanieId");

                    b.ToTable("Lekcja");
                });

            modelBuilder.Entity("DziennikMVC.Models.Nauczanie", b =>
                {
                    b.Property<int>("NauczanieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NauczycielId")
                        .HasColumnType("int");

                    b.Property<int>("PrzedmiotId")
                        .HasColumnType("int");

                    b.HasKey("NauczanieId");

                    b.HasIndex("NauczycielId");

                    b.HasIndex("PrzedmiotId");

                    b.ToTable("Nauczanie");
                });

            modelBuilder.Entity("DziennikMVC.Models.Nauczyciel", b =>
                {
                    b.Property<int>("NauczycielId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KontoId")
                        .HasColumnType("int");

                    b.HasKey("NauczycielId");

                    b.ToTable("Nauczyciel");
                });

            modelBuilder.Entity("DziennikMVC.Models.Obecnosc", b =>
                {
                    b.Property<int>("ObecnoscId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LekcjaId")
                        .HasColumnType("int");

                    b.Property<int?>("UczenId")
                        .HasColumnType("int");

                    b.Property<int>("obecnosc")
                        .HasColumnType("int");

                    b.HasKey("ObecnoscId");

                    b.HasIndex("LekcjaId");

                    b.HasIndex("UczenId");

                    b.ToTable("Obecnosc");
                });

            modelBuilder.Entity("DziennikMVC.Models.Ocena", b =>
                {
                    b.Property<int>("OcenaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NauczycielId")
                        .HasColumnType("int");

                    b.Property<int>("PrzedmiotId")
                        .HasColumnType("int");

                    b.Property<int>("UczenId")
                        .HasColumnType("int");

                    b.Property<int>("czy_koncowa")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("data")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ocena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opis_oceny")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OcenaId");

                    b.HasIndex("NauczycielId");

                    b.HasIndex("PrzedmiotId");

                    b.HasIndex("UczenId");

                    b.ToTable("Ocena");
                });

            modelBuilder.Entity("DziennikMVC.Models.Przedmiot", b =>
                {
                    b.Property<int>("PrzedmiotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dziedzina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrzedmiotId");

                    b.ToTable("Przedmiot");
                });

            modelBuilder.Entity("DziennikMVC.Models.Uczen", b =>
                {
                    b.Property<int>("UczenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KlasaId")
                        .HasColumnType("int");

                    b.Property<int>("KontoId")
                        .HasColumnType("int");

                    b.HasKey("UczenId");

                    b.HasIndex("KlasaId");

                    b.ToTable("Uczen");
                });

            modelBuilder.Entity("DziennikMVC.Models.Wiadomosc", b =>
                {
                    b.Property<int>("WiadomoscId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KontoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KontoId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NadawcaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdbiorcaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("czy_odczytana")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("data_wyslania")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("tresc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tytul")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WiadomoscId");

                    b.HasIndex("KontoId");

                    b.HasIndex("KontoId1");

                    b.ToTable("Wiadomosc");
                });

            modelBuilder.Entity("DziennikMVC.Models.Wydarzenie", b =>
                {
                    b.Property<int>("WydarzenieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KlasaId")
                        .HasColumnType("int");

                    b.Property<int?>("NauczycielId")
                        .HasColumnType("int");

                    b.Property<int>("PrzedmiotId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("data")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WydarzenieId");

                    b.HasIndex("KlasaId");

                    b.HasIndex("NauczycielId");

                    b.HasIndex("PrzedmiotId");

                    b.ToTable("Wydarzenie");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DziennikMVC.Models.Konto", b =>
                {
                    b.HasOne("DziennikMVC.Models.Nauczyciel", "Nauczyciel")
                        .WithMany()
                        .HasForeignKey("NauczycielId");

                    b.HasOne("DziennikMVC.Models.Uczen", "Uczen")
                        .WithMany()
                        .HasForeignKey("UczenId");
                });

            modelBuilder.Entity("DziennikMVC.Models.Lekcja", b =>
                {
                    b.HasOne("DziennikMVC.Models.Klasa", null)
                        .WithMany("Lekcje")
                        .HasForeignKey("KlasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DziennikMVC.Models.Nauczanie", null)
                        .WithMany("Lekcje")
                        .HasForeignKey("NauczanieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DziennikMVC.Models.Nauczanie", b =>
                {
                    b.HasOne("DziennikMVC.Models.Nauczyciel", null)
                        .WithMany("Nauczania")
                        .HasForeignKey("NauczycielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DziennikMVC.Models.Przedmiot", null)
                        .WithMany("Nauczania")
                        .HasForeignKey("PrzedmiotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DziennikMVC.Models.Obecnosc", b =>
                {
                    b.HasOne("DziennikMVC.Models.Lekcja", null)
                        .WithMany("Obecnosci")
                        .HasForeignKey("LekcjaId");

                    b.HasOne("DziennikMVC.Models.Uczen", null)
                        .WithMany("Obecnosci")
                        .HasForeignKey("UczenId");
                });

            modelBuilder.Entity("DziennikMVC.Models.Ocena", b =>
                {
                    b.HasOne("DziennikMVC.Models.Nauczyciel", null)
                        .WithMany("Oceny")
                        .HasForeignKey("NauczycielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DziennikMVC.Models.Przedmiot", null)
                        .WithMany("Oceny")
                        .HasForeignKey("PrzedmiotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DziennikMVC.Models.Uczen", null)
                        .WithMany("Oceny")
                        .HasForeignKey("UczenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DziennikMVC.Models.Uczen", b =>
                {
                    b.HasOne("DziennikMVC.Models.Klasa", null)
                        .WithMany("Uczniowie")
                        .HasForeignKey("KlasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DziennikMVC.Models.Wiadomosc", b =>
                {
                    b.HasOne("DziennikMVC.Models.Konto", null)
                        .WithMany("Wiadomosci_odebrane")
                        .HasForeignKey("KontoId");

                    b.HasOne("DziennikMVC.Models.Konto", null)
                        .WithMany("Wiadomosci_wyslane")
                        .HasForeignKey("KontoId1");
                });

            modelBuilder.Entity("DziennikMVC.Models.Wydarzenie", b =>
                {
                    b.HasOne("DziennikMVC.Models.Klasa", null)
                        .WithMany("Wydarzenie")
                        .HasForeignKey("KlasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DziennikMVC.Models.Nauczyciel", null)
                        .WithMany("Wydarzenia")
                        .HasForeignKey("NauczycielId");

                    b.HasOne("DziennikMVC.Models.Przedmiot", null)
                        .WithMany("Wydarzenia")
                        .HasForeignKey("PrzedmiotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DziennikMVC.Models.Konto", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DziennikMVC.Models.Konto", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DziennikMVC.Models.Konto", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DziennikMVC.Models.Konto", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
